create table if not exists activity_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  section text,
  detail text,
  document_type text,
  model_id text,
  device text,
  user_agent text
);

create index if not exists activity_events_created_at_idx on activity_events(created_at desc);
create index if not exists activity_events_event_type_idx on activity_events(event_type);
create index if not exists activity_events_section_idx on activity_events(section);
